### ISSUE TITLE
求助：怎样设置API KEY啊

### ISSUE THREAD

**Issue by getofferhelp** [weekend-project-space/eywa-chat#4]
大佬，我用Vercel部署了这个项目，后台和api/index.js里面都试着修改了GEMINI KEY，但是前台的页面还是不能正常使用。。

为啥啊，求助：这个gemini的key要怎样设置啊

救命...

**Comment by weekend-project-space** [comment]
修改这个文件 https://github.com/weekend-project-space/chat-gemini/blob/main/src/api/index.js
